### PR TITLE
Register classname for logSoftmax activation function

### PR DESCRIPTION
**Pull request by Derek-Wds**
This is about the issue [#998](https://github.com/tensorflow/tfjs/issues/998)
I have registered classname for the logSoftmax activation function in the `activations.ts`

Thanks

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/539)

### CODE REVIEW

**Comment by Derek-Wds** [comment]
I signed it!

**Comment by Derek-Wds** [comment]
@caisq Yeah Sure! Thanks for your information. I’m working on that.

Derek

**Comment by Derek-Wds** [comment]
@caisq Hi, I have changed the files following your comment. Please take a look!

Thanks,
Derek

**Comment by caisq** [comment]
There are test failures like this:

> Step #1 - "test-browser": 	Error: Arrays differ: actual[0] = -1.3862943649291992, expected[0] = 1.3860000371932983.

Can you use `expectTensorsClose()` instead of `expectTensorsEqual()`?

**Comment by caisq** [comment]
Actually, the sign seem to be wrong, can you also check the math?

**Comment by Derek-Wds** [comment]
I see. I will change that rn.

Thanks,
Derek

**Comment by Derek-Wds** [comment]
@caisq Hi, I have changed the foolish sign error that I made. This time should be fine.

Thanks,
Derek

**Pull request merged**
