### PR TITLE
Add onProgress to loadModel

### PR DESCRIPTION
**Pull request by syt123450**
FEATURE

This PR depends on [tensorflow/tfjs-core#1485](https://github.com/tensorflow/tfjs-core/pull/1485). Feature requests in [tensorflow/tfjs#336](https://github.com/tensorflow/tfjs/issues/336).  This PR adds onProgress feature to loadModel. Through this feature, developer can add callback function to tf.loadModel, the progress callback function will be fired periodically before the load is completed.

usage:
```
const loadedModel = await tf.loadModel(
    'Path/to/model/model.json',
    true,
    onProgress
);

function onProgress(percentage){ 
    console.log(percentage);
}

```

To show the usage of onProgress, I built a local version of tf.min.js ( including change in [tensorflow/tfjs-core#1485](https://github.com/tensorflow/tfjs-core/pull/1485), [tensorflow/tfjs-layers#413](https://github.com/tensorflow/tfjs-layers/pull/413),  [tensorflow/tfjs-converter#261](https://github.com/tensorflow/tfjs-converter/pull/261) ), and wrote a simple demo.
Online demo [link](https://syt123450.github.io/progress-demo/index.html)
Demo repository [link](https://github.com/syt123450/progress-demo)

Towards https://github.com/tensorflow/tfjs/issues/336

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/413)

### CODE REVIEW

**Comment by caisq** [comment]
@syt123450 FYI, we are doing some refactoring of the general model loading API in both tfjs-core and tfjs-layer. This PR of yours will be superseded by some of the changes.

**Comment by caisq** [comment]
@syt123450 But the foundation you laid in tfjs-core for progress callback will go into the upcoming TF.js 1.0 release for sure!

**Comment by caisq** [comment]
Closing this PR in favor of https://github.com/tensorflow/tfjs-layers/pull/459

**Comment by syt123450** [comment]
@caisq I have tried new `onProgress` feature in alpha version, new API looks clearer and easier to use. Thanks for adding this feature~

**Pull request closed without merging**
