### PR TITLE
Bump version to 0.7.2

### PR DESCRIPTION
**Pull request by caisq**
Depend on core version 0.12.6

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/272)

### CODE REVIEW

**Comment by caisq** [comment]
Thanks, @bileschi . Turns out that the latest changes in tfjs-core (in 0.12.6) is causing some test failures here. @nsthorat will fix that, after which I'll upgrade to 0.12.7 in this PR.

**Comment by caisq** [comment]
cc @dsmilkov and @nsthorat re test failures related to new ver of tfjs-core

**Comment by nsthorat** [comment]
PR to fix this error: https://github.com/tensorflow/tfjs-core/pull/1188

**Comment by nsthorat** [comment]
0.12.8 is released and should have the fix.

**Pull request merged**
