### PR TITLE
Remove -layer's reshape.

### PR DESCRIPTION
**Pull request by ericdnielsen**
Remove K.reshape in favor of tfc.reshape.

Initially changed the K.reshape implementation from x.reshape(shape) to tfc.reshape(x, shape), all tests pass.  Then removed K.reshape and adjusted all call sites to go direct to the core symbol.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/194)

### CODE REVIEW

**Comment by caisq** [comment]
Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---

*[src/backend/tfjs_backend.ts, line 167 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/194#-LCiOK6V2c7G3zt1YC4u:-LCiOK6V2c7G3zt1YC4v:bvqfsmw) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/4c489a8656fe0c3444dbef72273458517709ab07/src/backend/tfjs_backend.ts#L167)):*
> ```
>  tfc.reshape(x, outShape)
> ```

Prefer the "chaining API", i.e., `x.reshape(outShape)`. It is more concise and will save a line of import in some cases. Same below.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/194)*

**Comment by ericdnielsen** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/backend/tfjs_backend.ts, line 167 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/194#-LCiOK6V2c7G3zt1YC4u:-LCiSOI99QAa8ILx5DlH:bs7wumb) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/4c489a8656fe0c3444dbef72273458517709ab07/src/backend/tfjs_backend.ts#L167)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
>  tfc.reshape(x, outShape)
> ```

Prefer the "chaining API", i.e., `x.reshape(outShape)`. It is more concise and will save a line of import in some cases. Same below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/194)*

**Comment by caisq** [comment]
:lgtm_strong:

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/194#-:-LCiSTN88no81JcWJOhw:b-jbsf8z)*

**Comment by bileschi** [comment]
:lgtm_strong:

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/194#-:-LCiWFBp9DjiyYTV7uKI:b-jbsf8z)*

**Pull request merged**
