### PR TITLE
Support nested sequential models

### PR DESCRIPTION
**Pull request by caisq**
FEATURE

Fixes: https://github.com/tensorflow/tfjs/issues/398

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/226)

### CODE REVIEW

**Comment by caisq** [comment]
@bileschi please hold off reviewing. I'm adding some more checks and tests. I'll send a signal when it's ready.

**Comment by bileschi** [comment]
:lgtm_strong:  Thought:  Does it make sense to test the functional Model API too, or is that over testing?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[src/models_test.ts, line 24 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/226#-LELdJz4Bul1GN39gGf8:-LELdJz4Bul1GN39gGf9:b-9sk7tl) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/48f84d37d8687ea093e9b746fb7ac160ca5be54d/src/models_test.ts#L24)):*
> ```
> export
> ```
Maybe don't need export here?  Also, this seems to be an artifact from an unrelated PR?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/226#-:-LELeAdv1ii80Ib2u_Pn:bhjzgsp)*

**Comment by caisq** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/models_test.ts, line 24 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/226#-LELdJz4Bul1GN39gGf8:-LENMHYu3qdjGa0tcYM6:b-8rsxtz) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/48f84d37d8687ea093e9b746fb7ac160ca5be54d/src/models_test.ts#L24)):*
<details><summary><i>Previously, bileschi (Stanley Bileschi) wrote…</i></summary><blockquote>

> ```
> export
> ```
Maybe don't need export here?  Also, this seems to be an artifact from an unrelated PR?
</blockquote></details>

Oops. Remove the cruft. Thanks for catching that. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/226)*

**Comment by caisq** [comment]
@bileschi Ready for another look.

**Comment by bileschi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/models_test.ts, line 168 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/226#-LENYu4xDMOpe-pYn3CK:-LENYu4xDMOpe-pYn3CL:b-8apeon) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/d2a815edece030b918ec4cf7ae421f3486bf3d7c/src/models_test.ts#L168)):*
> ```XML
>     expect(outerModel.getLayer(null, 0) instanceof tfl.Sequential)
>         .toEqual(true);
>     expectTensorsClose(
> ```

Maybe add comment, initialized weights are expected to be one because of the initializers

---

*[src/models_test.ts, line 171 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/226#-LENYrT55C2Rc8n3D_GQ:-LENYrT55C2Rc8n3D_GR:bfvp35l) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/d2a815edece030b918ec4cf7ae421f3486bf3d7c/src/models_test.ts#L171)):*
> ```XML
>         outerModel.getLayer(null, 1).getWeights()[0], ones([2, 1]));
>     expectTensorsClose(outerModel.getLayer(null, 1).getWeights()[1], ones([1]));
>     expect(() => outerModel.getLayer(null, 2)).toThrow();
> ```

Maybe add comment : there are only 2 layers

---

*[src/models_test.ts, line 204 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/226#-LENZSC39ggcBbHu_fQk:-LENZSC39ggcBbHu_fQl:bs3eon9) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/d2a815edece030b918ec4cf7ae421f3486bf3d7c/src/models_test.ts#L204)):*
> ```
> getWeights() works for nested sequential model
> ```
This is the same name as the above test.  Probably meant 'setWeights'?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/226)*

**Comment by caisq** [comment]
@bileschi In case you need to take another look.

**Pull request merged**
