### PR TITLE
Apply tidy/@operation systematically across tfjs-layers.

### PR DESCRIPTION
**Pull request by ericdnielsen**
The need to tidy every call in layers came out of another PR review.  This PR shows a prototype version of the anticipated changes on a single file, wanted to get feedback before I start applying the same pattern everywhere.

Our stated approach:
1) use @operation on every class method.
2) use tidy on every non-class method.

I've taken this literally, even on methods that I don't think could leak, but I think the consensus was full coverage was worth the possible performance hits.

I'm not currently tidy-ing constructors, (can we?  does that make sense?)

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/186)

### CODE REVIEW

**Comment by caisq** [comment]
Review status: 0 of 17 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/activations.ts, line 51 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCb1QxH974USb5mmxNP:-LCb1QxH974USb5mmxNQ:b-k71s0g) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/f12cbc6f8262db7325822c18ff35473c7edaff14/src/activations.ts#L51)):*
> ```
>     return tidy(() => {
>       return K.elu(x, alpha);
>     });
> ```

Function bodies with a single return statement like this can be simplified as:

```
return tidy(() => K.elu(x, alpha));
```

This applies to many other instances like this below.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/186)*

**Comment by ericdnielsen** [comment]
Review status: 0 of 17 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/activations.ts, line 51 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCb1QxH974USb5mmxNP:-LCdAVjn8KIrXaEuVS0t:bjw3c0c) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/f12cbc6f8262db7325822c18ff35473c7edaff14/src/activations.ts#L51)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
>     return tidy(() => {
>       return K.elu(x, alpha);
>     });
> ```

Function bodies with a single return statement like this can be simplified as:

```
return tidy(() => K.elu(x, alpha));
```

This applies to many other instances like this below.
</blockquote></details>

I had formatted most of those that way, clang-format sometimes wraps them.  I'll try reformatting them back to one line, but I'm suspect it will undo it again.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/186)*

**Comment by nsthorat** [comment]
:lgtm_strong:

Comments are all duplicate so ignore the volume :)

---

Review status: 0 of 17 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/activations.ts, line 51 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCb1QxH974USb5mmxNP:-LCdH4JD9ehyG7J3CjzE:be414cb) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/f12cbc6f8262db7325822c18ff35473c7edaff14/src/activations.ts#L51)):*
<details><summary><i>Previously, ericdnielsen wrote…</i></summary><blockquote>

I had formatted most of those that way, clang-format sometimes wraps them.  I'll try reformatting them back to one line, but I'm suspect it will undo it again.
</blockquote></details>

this method takes x in and produces a single y with no intermediates, so you don't have to call tidy for this method. I will mark those locations as well.

---

*[src/activations.ts, line 65 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdHToo5G3hAvjVBxXj:-LCdHToo5G3hAvjVBxXk:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/activations.ts#L65)):*
> ```XML
>   static readonly className = 'selu';
>   apply(x: Tensor): Tensor {
>     return tidy(() => tfc.selu(x));
> ```

no need for tidy, no intermediates

---

*[src/activations.ts, line 76 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdHWxD5pkgfidzKxSz:-LCdHWxD5pkgfidzKxT-:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/activations.ts#L76)):*
> ```XML
>   static readonly className = 'relu';
>   apply(x: Tensor): Tensor {
>     return tidy(() => tfc.relu(x));
> ```

no need for tidy, no intermediates

---

*[src/activations.ts, line 99 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdHXpS6o74-Lq-Dfy2:-LCdH8GH5kC80Cl6Opcg:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/activations.ts#L99)):*
> ```XML
>   static readonly className = 'linear';
>   apply(x: Tensor): Tensor {
>     return tidy(() => x);
> ```

no need for tidy, no intermediates

---

*[src/activations.ts, line 110 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdHYWrAKxK-2SaSueu:-LCdHYWsD8BNEIdlLwaA:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/activations.ts#L110)):*
> ```XML
>   static readonly className = 'sigmoid';
>   apply(x: Tensor): Tensor {
>     return tidy(() => tfc.sigmoid(x));
> ```

no need for tidy, no intermediates

---

*[src/activations.ts, line 121 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdHZ0k0NIiyqIasWMX:-LCdHZ0k0NIiyqIasWMY:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/activations.ts#L121)):*
> ```XML
>   static readonly className = 'hardSigmoid';
>   apply(x: Tensor): Tensor {
>     return tidy(() => K.hardSigmoid(x));
> ```

no need for tidy, no intermediates

---

*[src/activations.ts, line 132 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdHZWD4yZE7G8N7tGz:-LCdHZWD4yZE7G8N7tH-:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/activations.ts#L132)):*
> ```XML
>   static readonly className = 'softplus';
>   apply(x: Tensor): Tensor {
>     return tidy(() => K.softplus(x));
> ```

no need for tidy, no intermediates

---

*[src/activations.ts, line 143 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdH_1GEKOMyAX2EQ1l:-LCdH_1GEKOMyAX2EQ1m:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/activations.ts#L143)):*
> ```XML
>   static readonly className = 'softsign';
>   apply(x: Tensor): Tensor {
>     return tidy(() => K.softsign(x));
> ```

no need for tidy, no intermediates

---

*[src/activations.ts, line 154 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdH_Q221FkLL7423LL:-LCdH_Q221FkLL7423LM:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/activations.ts#L154)):*
> ```XML
>   static readonly className = 'tanh';
>   apply(x: Tensor): Tensor {
>     return tidy(() => tfc.tanh(x));
> ```

no need for tidy, no intermediates

---

*[src/activations.ts, line 177 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdH_wxEszXTKPKAupR:-LCdH_wxEszXTKPKAupS:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/activations.ts#L177)):*
> ```XML
>    */
>   apply(x: Tensor, axis: number = (-1)): Tensor {
>     return tidy(() => tfc.softmax(x, axis));
> ```

no need for tidy, no intermediates

---

*[src/constraints.ts, line 154 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdHbML3bEf8DQY8EiG:-LCdHbML3bEf8DQY8EiH:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/constraints.ts#L154)):*
> ```XML
> 
>   apply(w: Tensor): Tensor {
>     return tidy(() => tfc.relu(w));
> ```

no need for tidy, no intermediates

---

*[src/initializers.ts, line 66 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdHcOz8kJ0XmG51xGl:-LCdHcOz8kJ0XmG51xGm:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/initializers.ts#L66)):*
> ```XML
> 
>   apply(shape: Shape, dtype?: DataType): Tensor {
>     return tidy(() => zeros(shape, dtype));
> ```

no need for tidy, no intermediates

---

*[src/initializers.ts, line 78 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdHd2e9_xqWdW8OAUG:-LCdHd2e9_xqWdW8OAUH:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/initializers.ts#L78)):*
> ```XML
> 
>   apply(shape: Shape, dtype?: DataType): Tensor {
>     return tidy(() => ones(shape, dtype));
> ```

no need for tidy, no intermediates

---

*[src/initializers.ts, line 144 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdHe5K1gsxj1II1Feg:-LCdHe5K1gsxj1II1Feh:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/initializers.ts#L144)):*
> ```XML
> 
>   apply(shape: Shape, dtype?: DataType): Tensor {
>     return tidy(() => randomUniform(shape, this.minval, this.maxval, dtype));
> ```

no need for tidy, no intermediates

---

*[src/initializers.ts, line 187 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdHeohE7gvaAYbVP4g:-LCdHeohE7gvaAYbVP4h:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/initializers.ts#L187)):*
> ```XML
>             `randomNormal does not support dType bool.`);
>       }
>       return K.randomNormal(shape, this.mean, this.stddev, dtype, this.seed);
> ```

no need for tidy, no intermediates

---

*[src/initializers.ts, line 236 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdHfWT-fT52MTOTgi3:-LCdHfWT-fT52MTOTgi4:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/initializers.ts#L236)):*
> ```XML
>             `truncatedNormal does not support dType bool.`);
>       }
>       return truncatedNormal(shape, this.mean, this.stddev, dtype, this.seed);
> ```

no need for tidy, no intermediates

---

*[src/initializers.ts, line 392 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdHjGI-moB6hfiBv9_:-LCdHjGI-moB6hfiBv9a:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/initializers.ts#L392)):*
> ```XML
>       } else {
>         const limit = Math.sqrt(3 * scale);
>         return randomUniform(shape, -limit, limit, dtype);
> ```

no need for tidy, no intermediates

---

*[src/backend/tfjs_backend.ts, line 241 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdHqOL05NiJ1Vn_vxr:-LCdHqOL05NiJ1Vn_vxs:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/backend/tfjs_backend.ts#L241)):*
> ```XML
> export function sliceAlongFirstAxis(
>     array: Tensor, start: number, size: number): Tensor {
>   return tidy(() => {
> ```

no need for tidy, no intermediates

---

*[src/backend/tfjs_backend.ts, line 273 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdHpfKAnTb1TcB4eLx:-LCdHpfKAnTb1TcB4eLy:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/backend/tfjs_backend.ts#L273)):*
> ```XML
>  */
> export function sliceAlongLastAxis(
>     array: Tensor, start: number, size: number): Tensor {
> ```

no need for tidy, no intermediates

---

*[src/layers/convolutional.ts, line 45 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdHylrDdWg7ABuuJDI:-LCdHylrDdWg7ABuuJDJ:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/layers/convolutional.ts#L45)):*
> ```XML
>     checkDataFormat(dataFormat);
>     if (dataFormat === 'channelsFirst') {
>       return tfc.transpose(x, [0, 2, 3, 1]);  // NCHW -> NHWC.
> ```

no need for tidy, no intermediates

---

*[src/layers/convolutional.ts, line 128 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdI-Nt76B84WzNGx5w:-LCdI-Nt76B84WzNGx5x:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/layers/convolutional.ts#L128)):*
> ```XML
>   return tidy(() => {
>     checkDataFormat(dataFormat);
>     return conv1dWithBias(
> ```

no need for tidy, no intermediates

---

*[src/layers/convolutional.ts, line 148 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdHzwN0pFZBiDof0dV:-LCdHzwN0pFZBiDof0dW:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/layers/convolutional.ts#L148)):*
> ```XML
>   return tidy(() => {
>     checkDataFormat(dataFormat);
>     return conv2dWithBias(
> ```

no need for tidy, no intermediates

---

*[src/layers/core.ts, line 474 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdI4uO8a40kU3tClBB:-LCdI4uO8a40kU3tClBC:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/layers/core.ts#L474)):*
> ```XML
>     return tidy(() => {
>       inputs = getExactlyOneTensor(inputs);
>       return K.repeat(inputs, this.n);
> ```

no need for tidy, no intermediates

---

*[src/layers/merge.ts, line 776 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdIAg84oRbBw8HWGoI:-LCdIAg84oRbBw8HWGoJ:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/layers/merge.ts#L776)):*
> ```XML
> 
>   protected mergeFunction(inputs: Tensor[]): Tensor {
>     return tidy(() => {
> ```

no need for tidy, no intermediates

---

*[src/layers/padding.ts, line 249 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdIKqN4NbeXNrkrIff:-LCdIKqN4NbeXNrkrIfg:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/layers/padding.ts#L249)):*
> ```XML
>   call(inputs: Tensor|Tensor[], kwargs: Kwargs): Tensor|Tensor[] {
>     return tidy(
>         () => spatial2dPadding(
> ```

no need for tidy, no intermediates

---

*[src/layers/pooling.ts, line 413 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdINQt8BMUJEwOoFid:-LCdINQt8BMUJEwOoFie:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/layers/pooling.ts#L413)):*
> ```XML
>     return tidy(() => {
>       const input = generic_utils.getExactlyOneTensor(inputs);
>       return tfc.mean(input, 1);
> ```

no need for tidy, no intermediates

---

*[src/layers/pooling.ts, line 435 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdIMorCTkguhUUJ7Cz:-LCdIMorCTkguhUUJ7D-:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/layers/pooling.ts#L435)):*
> ```XML
>     return tidy(() => {
>       const input = generic_utils.getExactlyOneTensor(inputs);
>       return tfc.max(input, 1);
> ```

no need for tidy, no intermediates

---

*[src/layers/pooling.ts, line 503 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdIP8a4rAzgY5WQtLz:-LCdIP8a4rAzgY5WQtM-:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/layers/pooling.ts#L503)):*
> ```XML
> 
>   call(inputs: Tensor|Tensor[], kwargs: Kwargs): Tensor|Tensor[] {
>     return tidy(() => {
> ```

no need for tidy, no intermediates

---

*[src/layers/pooling.ts, line 531 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-LCdIPfK6dNQ0_7jGIsS:-LCdIPfK6dNQ0_7jGIsT:b-uo7jvk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/0180c15670113a6f17341c63f10ccbfc83a5dd33/src/layers/pooling.ts#L531)):*
> ```XML
> 
>   call(inputs: Tensor|Tensor[], kwargs: Kwargs): Tensor|Tensor[] {
>     return tidy(() => {
> ```

no need for tidy, no intermediates

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-:-LCdIVdN-By1_3srm6eJ:bhtbnml)*

**Comment by caisq** [comment]
:lgtm_strong:

Thanks for these improvements. Before the next release, we should 
1) Profile speed to make sure there is no substantial negative impact of these changes on performance
2) (maybe at a later point) quantify the memory saving due to these changes.

---

Review status: 0 of 17 files reviewed at latest revision, 30 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/186#-:-LCdLpv06vwJ7AYcKuIy:b9ldl5w)*

**Pull request merged**
