### PR TITLE
 Fix a few Camel- vs. Snake- case issues in keras_format.

### PR DESCRIPTION
**Pull request by davidsoergel**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/490)

### CODE REVIEW

**Comment by bileschi** [comment]
Is this ready to submit?  Is there something that is blocking this?

**Comment by nsthorat** [comment]
Is this a breaking change?

**Comment by bileschi** [comment]
I don't think anything depends on keras_format yet, and the tests pass, so I'm inclined to volunteer that the answer is no.  @ericdnielsen do you know anything about this change?  Is it safe to submit?

**Comment by ericdnielsen** [comment]
I'm pretty sure its safe/non-breaking.

**Pull request merged**
