### PR TITLE
Add assertions for positive-integer values

### PR DESCRIPTION
**Pull request by caisq**
FEATURE
UX

Fixes https://github.com/tensorflow/tfjs/issues/882

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/457)

### CODE REVIEW

**Comment by nsthorat** [comment]
FYI I'm also doing this in core: https://github.com/tensorflow/tfjs-core/pull/1562

**Comment by caisq** [comment]
@nsthorat Doing it in the core is useful. However, I think making assertions at the level of tfjs-layers still helps, because it leads to clearer error messages. WDYT?

**Comment by nsthorat** [comment]
Oh yeah I wasn't saying ditch this PR -- this should absolutely happen here too!

**Comment by caisq** [comment]
@nsthorat yeah, I considered using JSON.stringify(). The problem: it is expensive and sometimes leads to undesirable effects. For example, if someone accidentally passes a Model or Layer object as the value of units, it'll lead to a failure to convert to JSON or a huge error message containing a new JSON string.

**Pull request merged**
