### PR TITLE
Adding dropout implmentation to RNNs

### PR DESCRIPTION
**Pull request by ericdnielsen**
Not ready for review yet.  Still need testing, etc.  But getting into a PR for easier comparison.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/203)

### CODE REVIEW

**Comment by ericdnielsen** [comment]
Tests added, ready for review

**Comment by caisq** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[src/layers/recurrent.ts, line 1018 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWGgf6Ax6T-QBveVTu:-LGWGgf743ID5CPkEcUX:bjuk6a8) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/59e73aedbc5ee21152c4aac1aa872d45e1dfc3f4/src/layers/recurrent.ts#L1018)):*
> ```
>         this.dropoutMask = generateDropoutMask(() => {
>                              return tfc.onesLike(inputs as Tensor);
>                            }, this.dropout, training) as Tensor;
> ```

This can be simplified as `() => tfc.onesLike(input as Tensor)`. Same elsewhere.

---

*[src/layers/recurrent.ts, line 1024 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWG_9j3ud2CZtNkIsZ:-LGWG_9j3ud2CZtNkIs_:bimcibr) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/59e73aedbc5ee21152c4aac1aa872d45e1dfc3f4/src/layers/recurrent.ts#L1024)):*
> ```
>             generateDropoutMask(() => {
>               return tfc.onesLike(prevOutput);
>             }, this.recurrentDropout, training) as Tensor;
> ```

This can be simplified as `() => tfc.onesLike(prevOutput)`. Same elsewhere.

---

*[src/layers/recurrent.ts, line 1474 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWHlz-9R8-n1zCu7I_:-LGWHlz-9R8-n1zCu7Ia:b1cgqsm) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/59e73aedbc5ee21152c4aac1aa872d45e1dfc3f4/src/layers/recurrent.ts#L1474)):*
> ```
> Tensor[]
> ```

Optional: Would be slightly safer to type this as `[Tensor, Tensor, Tensor]`. Same below.

---

*[src/layers/recurrent.ts, line 2513 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWDhcK46Hj87BWwBTT:-LGWDhcK46Hj87BWwBTU:b77dfh3) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/59e73aedbc5ee21152c4aac1aa872d45e1dfc3f4/src/layers/recurrent.ts#L2513)):*
> ```
> training = training)
> ```

s/training = training/training/

Same below.

---

*[src/layers/recurrent_test.ts, line 540 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWJ5HiEpZ1FMfY5yvs:-LGWJ5HiEpZ1FMfY5yvt:b-5cyjt1) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/59e73aedbc5ee21152c4aac1aa872d45e1dfc3f4/src/layers/recurrent_test.ts#L540)):*
> ```
> dropouts = [0.0, 0.1];
> ```

Can we add tests for recurrentDropout > 0 and < 1?

---

*[src/layers/recurrent_test.ts, line 548 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWJdWh9Fl5zZfFnOz0:-LGWJdWh9Fl5zZfFnOz1:bnqkn3v) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/59e73aedbc5ee21152c4aac1aa872d45e1dfc3f4/src/layers/recurrent_test.ts#L548)):*
> ```
> 1
> ```

For generality, can we make this a larger number?

---

*[src/layers/recurrent_test.ts, line 565 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWJNPF8BmU70h397h4:-LGWJNPF8BmU70h397h5:b-ogx2ee) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/59e73aedbc5ee21152c4aac1aa872d45e1dfc3f4/src/layers/recurrent_test.ts#L565)):*
> ```
> 1
> ```

This should be 1 regardless of `timeSteps`, right? (No change required. Just confirming.)

---

*[src/layers/recurrent_test.ts, line 582 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWJXy5-S3yZvdTp-fh:-LGWJXy5-S3yZvdTp-fi:b-aicbb) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/59e73aedbc5ee21152c4aac1aa872d45e1dfc3f4/src/layers/recurrent_test.ts#L582)):*
> ```
> 1
> ```

As above, we can make this a larger number?

---

*[src/layers/recurrent_test.ts, line 602 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWKMB9-7JEStDlnkLI:-LGWKMBAAt3FNm4NjFzc:b-q6xkw8) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/59e73aedbc5ee21152c4aac1aa872d45e1dfc3f4/src/layers/recurrent_test.ts#L602)):*
> ```
> }
> ```

Add an `else` branch with assertions in it.

---

*[src/layers/recurrent_test.ts, line 912 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWJy3z7QHRiDdyWTOZ:-LGWJy4--2ZSwEpl2ita:b-4fyp6a) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/59e73aedbc5ee21152c4aac1aa872d45e1dfc3f4/src/layers/recurrent_test.ts#L912)):*
> ```
> }
> ```

this needs an `else` branch with assertions in it.

---

*[src/layers/recurrent_test.ts, line 1235 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWK4rX5XccipYfCcCH:-LGWK4rX5XccipYfCcCI:b-j7faoi) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/59e73aedbc5ee21152c4aac1aa872d45e1dfc3f4/src/layers/recurrent_test.ts#L1235)):*
> ```
> }
> ```

This needs an `else` branch with assertions in it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/203)*

**Comment by ericdnielsen** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[src/layers/recurrent.ts, line 1018 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWGgf6Ax6T-QBveVTu:-LGWN4iNCPlsXEwXAcPU:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/59e73aedbc5ee21152c4aac1aa872d45e1dfc3f4/src/layers/recurrent.ts#L1018)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
>         this.dropoutMask = generateDropoutMask(() => {
>                              return tfc.onesLike(inputs as Tensor);
>                            }, this.dropout, training) as Tensor;
> ```

This can be simplified as `() => tfc.onesLike(input as Tensor)`. Same elsewhere.
</blockquote></details>

Done.

---

*[src/layers/recurrent.ts, line 1024 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWG_9j3ud2CZtNkIsZ:-LGWN58k3OpSXKmjUnkD:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/59e73aedbc5ee21152c4aac1aa872d45e1dfc3f4/src/layers/recurrent.ts#L1024)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
>             generateDropoutMask(() => {
>               return tfc.onesLike(prevOutput);
>             }, this.recurrentDropout, training) as Tensor;
> ```

This can be simplified as `() => tfc.onesLike(prevOutput)`. Same elsewhere.
</blockquote></details>

Done.

---

*[src/layers/recurrent.ts, line 1474 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWHlz-9R8-n1zCu7I_:-LGWNIpNDdcqQJaM3GdQ:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/59e73aedbc5ee21152c4aac1aa872d45e1dfc3f4/src/layers/recurrent.ts#L1474)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> Tensor[]
> ```

Optional: Would be slightly safer to type this as `[Tensor, Tensor, Tensor]`. Same below.
</blockquote></details>

Done.

---

*[src/layers/recurrent.ts, line 2513 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWDhcK46Hj87BWwBTT:-LGWNRi8EuQxY5tZbE7J:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/59e73aedbc5ee21152c4aac1aa872d45e1dfc3f4/src/layers/recurrent.ts#L2513)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> training = training)
> ```

s/training = training/training/

Same below.
</blockquote></details>

Done.

---

*[src/layers/recurrent_test.ts, line 540 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWJ5HiEpZ1FMfY5yvs:-LGWNnZ06TOY2PJ6OdsY:b-fqhksv) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/59e73aedbc5ee21152c4aac1aa872d45e1dfc3f4/src/layers/recurrent_test.ts#L540)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> dropouts = [0.0, 0.1];
> ```

Can we add tests for recurrentDropout > 0 and < 1?
</blockquote></details>

discussed, offline.

---

*[src/layers/recurrent_test.ts, line 548 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWJdWh9Fl5zZfFnOz0:-LGWO4j3BJq2dsadJwge:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/59e73aedbc5ee21152c4aac1aa872d45e1dfc3f4/src/layers/recurrent_test.ts#L548)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> 1
> ```

For generality, can we make this a larger number?
</blockquote></details>

Done.

---

*[src/layers/recurrent_test.ts, line 565 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWJNPF8BmU70h397h4:-LGWOgPo3Z9JbRPuitYx:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/59e73aedbc5ee21152c4aac1aa872d45e1dfc3f4/src/layers/recurrent_test.ts#L565)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> 1
> ```

This should be 1 regardless of `timeSteps`, right? (No change required. Just confirming.)
</blockquote></details>

Done.

---

*[src/layers/recurrent_test.ts, line 582 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWJXy5-S3yZvdTp-fh:-LGWO5_lAQTVA4RwiYqn:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/59e73aedbc5ee21152c4aac1aa872d45e1dfc3f4/src/layers/recurrent_test.ts#L582)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> 1
> ```

As above, we can make this a larger number?
</blockquote></details>

Done.

---

*[src/layers/recurrent_test.ts, line 602 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWKMB9-7JEStDlnkLI:-LGWOfW53qrWqcxrabkY:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/59e73aedbc5ee21152c4aac1aa872d45e1dfc3f4/src/layers/recurrent_test.ts#L602)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> }
> ```

Add an `else` branch with assertions in it.
</blockquote></details>

Done.

---

*[src/layers/recurrent_test.ts, line 912 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWJy3z7QHRiDdyWTOZ:-LGWOf4V8BQ0IfD1pZ7C:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/59e73aedbc5ee21152c4aac1aa872d45e1dfc3f4/src/layers/recurrent_test.ts#L912)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> }
> ```

this needs an `else` branch with assertions in it.
</blockquote></details>

Done.

---

*[src/layers/recurrent_test.ts, line 1235 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWK4rX5XccipYfCcCH:-LGWOeTX7YLCoN-jqk4y:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/59e73aedbc5ee21152c4aac1aa872d45e1dfc3f4/src/layers/recurrent_test.ts#L1235)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> }
> ```

This needs an `else` branch with assertions in it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/203)*

**Comment by caisq** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[src/layers/recurrent.ts, line 1474 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWHlz-9R8-n1zCu7I_:-LGWeqdL2kB3o3Gpns_Z:bp6bqmi) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/59e73aedbc5ee21152c4aac1aa872d45e1dfc3f4/src/layers/recurrent.ts#L1474)):*
<details><summary><i>Previously, ericdnielsen wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You say it's done. But I don't see any changes made here?

---

*[src/layers/recurrent_test.ts, line 542 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWgqeJ7GcC4aDAW2YW:-LGWgqeJ7GcC4aDAW2YX:b-rou2rk) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/17fedbde7162d1420cd178a0165b7d6d83ddf5cb/src/layers/recurrent_test.ts#L542)):*
> ```
> for (const training of trainings) {
> ```

For tests like this, can we add the following check for the absence of memory leak? 

After the 1st iteration, call `tfc.memory().numTensors` to get the number of tensors in the backend.
After the 2nd iteration, get that number again and assert that it should be equal to the previous number.

---

*[src/layers/recurrent_test.ts, line 566 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWf28o2ilPnAyafnUD:-LGWf28o2ilPnAyafnUE:b-sfy6wo) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/17fedbde7162d1420cd178a0165b7d6d83ddf5cb/src/layers/recurrent_test.ts#L566)):*
> ```
> 1  *
> ```

Is there any reason to keep this `1 * ` here? Same below?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/203)*

**Comment by ericdnielsen** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[src/layers/recurrent.ts, line 1474 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWHlz-9R8-n1zCu7I_:-LGWi0zK9MPQlQGeqZbw:bydu16z) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/59e73aedbc5ee21152c4aac1aa872d45e1dfc3f4/src/layers/recurrent.ts#L1474)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

You say it's done. But I don't see any changes made here?
</blockquote></details>

Ahh I changed the LSTM ones, not the GRU ones.  Both are changed now.

---

*[src/layers/recurrent_test.ts, line 542 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWgqeJ7GcC4aDAW2YW:-LGWko8x5tKJ9V7J-aEO:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/17fedbde7162d1420cd178a0165b7d6d83ddf5cb/src/layers/recurrent_test.ts#L542)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> for (const training of trainings) {
> ```

For tests like this, can we add the following check for the absence of memory leak? 

After the 1st iteration, call `tfc.memory().numTensors` to get the number of tensors in the backend.
After the 2nd iteration, get that number again and assert that it should be equal to the previous number.
</blockquote></details>

Done.

---

*[src/layers/recurrent_test.ts, line 566 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWf28o2ilPnAyafnUD:-LGWiJs238MkwJtKl_Up:b-1gh2ha) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/17fedbde7162d1420cd178a0165b7d6d83ddf5cb/src/layers/recurrent_test.ts#L566)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> 1  *
> ```

Is there any reason to keep this `1 * ` here? Same below?
</blockquote></details>

I think, compared to the GRU & LSTM ones, where its not 1 *, the parallelism is useful.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/203)*

**Comment by caisq** [comment]
:lgtm_strong:

Thanks!

---

Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[src/layers/recurrent.ts, line 2009 at r4](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWlLOuEazSMKGqPDNe:-LGWlLOvDQw9GENM3vSP:bkvig9v) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/60b1603df0e15cd5e63cf6aa5b1c37b43d0ec78c/src/layers/recurrent.ts#L2009)):*
> ```
> [Tensor, Tensor, Tensor];
> ```

Isn't this supposed to be four (instead of three) Tensors? Same in the line below.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-:-LGWlRU-EvU1w78pxGe6:b-afugb9)*

**Comment by ericdnielsen** [comment]
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[src/layers/recurrent.ts, line 2009 at r4](https://reviewable.io/reviews/tensorflow/tfjs-layers/203#-LGWlLOuEazSMKGqPDNe:-LGWlsokDjkqDasNpRu2:b-bh97a4) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/60b1603df0e15cd5e63cf6aa5b1c37b43d0ec78c/src/layers/recurrent.ts#L2009)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> [Tensor, Tensor, Tensor];
> ```

Isn't this supposed to be four (instead of three) Tensors? Same in the line below.
</blockquote></details>

Looks like it should be, not sure why TS & lint don't complain.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/203)*

**Pull request merged**
