### PR TITLE
Fix WebGL memory leak during Model.fit() call with callbacks

### PR DESCRIPTION
**Pull request by caisq**
BUG

Fixes https://github.com/tensorflow/tfjs/issues/457

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/252)

### CODE REVIEW

**Comment by bileschi** [comment]
:lgtm_strong:

---

Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[src/base_callbacks.ts, line 325 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/252#-LG1tHwt38rEXJCl2C67:-LG1tHwt38rEXJCl2C68:bw2xfjv) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/82498bf8b4c3c6ba00bd5d4572fe4383e59649c0/src/base_callbacks.ts#L325)):*
> ```
>       const tensorToDispose = this.history[keys[n]][indices[n]] as Tensor;
>       tensorToDispose.dispose();
> ```
Is this functionally different?  Or is this just a syntax change?  

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/252#-:-LG1uNGCAO3QCm4gGsWa:b-jbsf8z)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: :shipit: complete! 2 of 1 LGTMs obtained

---

*[src/engine/training_test.ts, line 1591 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/252#-LG1v9zP5vnYXEyuqFm5:-LG1v9zP5vnYXEyuqFm6:bs9whh7) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/82498bf8b4c3c6ba00bd5d4572fe4383e59649c0/src/engine/training_test.ts#L1591)):*
> ```XML
>          validationSplit,
>          callbacks: {
>            onBatchEnd: async () => {},
> ```

no need for this callback I think

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/252#-:-LG1vw1PCeJEeGZknwih:b-jbsf8z)*

**Comment by dsmilkov** [comment]
:lgtm_strong:

---

Review status: :shipit: complete! 3 of 1 LGTMs obtained

---

*[src/logs.ts, line 49 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/252#-LG28ATFE_1ZrrkKz3zG:-LG28ATFE_1ZrrkKz3zH:b-6v6u28) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/82498bf8b4c3c6ba00bd5d4572fe4383e59649c0/src/logs.ts#L49)):*
> ```XML
> 
>   // Dispose the original scalar tensors.
>   scalarsToDispose.forEach(scalar => scalar.dispose());
> ```

use tf.dispose(scalarsToDispose). It will do the forEach for you. tf.dispose() accepts any arbitrarily nested container.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/252#-:-LG28LQLEKDrV95P9f9R:b-jbsf8z)*

**Comment by caisq** [comment]
Review status: :shipit: complete! 3 of 1 LGTMs obtained

---

*[src/base_callbacks.ts, line 325 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/252#-LG1tHwt38rEXJCl2C67:-LG2KpNk02tSkAUDZgEL:b-gaq72x) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/82498bf8b4c3c6ba00bd5d4572fe4383e59649c0/src/base_callbacks.ts#L325)):*
<details><summary><i>Previously, bileschi (Stanley Bileschi) wrote…</i></summary><blockquote>

> ```
>       const tensorToDispose = this.history[keys[n]][indices[n]] as Tensor;
>       tensorToDispose.dispose();
> ```
Is this functionally different?  Or is this just a syntax change?  
</blockquote></details>

It is functionally equivalent. I just did this to increase the readability of the code.

---

*[src/logs.ts, line 49 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/252#-LG28ATFE_1ZrrkKz3zG:-LG2LloM0m5uUB-TMJbS:b-qkii48) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/82498bf8b4c3c6ba00bd5d4572fe4383e59649c0/src/logs.ts#L49)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

use tf.dispose(scalarsToDispose). It will do the forEach for you. tf.dispose() accepts any arbitrarily nested container.
</blockquote></details>

Good to know. Done.

---

*[src/engine/training_test.ts, line 1591 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/252#-LG1v9zP5vnYXEyuqFm5:-LG2Mjy80pf-3eWCGTJB:b4ym3w0) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/82498bf8b4c3c6ba00bd5d4572fe4383e59649c0/src/engine/training_test.ts#L1591)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

no need for this callback I think
</blockquote></details>

True. Done. Also done in the `it` above.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/252)*

**Pull request merged**
