### PR TITLE
Add prelu layer

### PR DESCRIPTION
**Pull request by rouismia**
#### Description
Add advanced_activations_PReLU

---
##### For repository owners only:

Please remember to apply all applicable tags to your pull request.
Tags: FEATURE, BREAKING, BUG, PERF, DEV, DOC, SECURITY

For more info see: https://github.com/tensorflow/tfjs/blob/master/DEVELOPMENT.md

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/381)

### CODE REVIEW

**Comment by rouismia** [comment]
i signed it

2018년 11월 21일 (수) 20:32에 googlebot <notifications@github.com>님이 작성:

**Comment by caisq** [comment]
@rouismia Gentle ping. Any chance you can address the comments soon so we can push this PR forward? Thanks.

**Comment by rouismia** [comment]
i think it needs modify tfjs-core's prelu
so as soon as possible i should change this, but it takes a little bit time

**Comment by rouismia** [comment]
sorry, i didn't know core's already changed. i should check some codes and commit soon

**Comment by rouismia** [comment]
I'm not sure it's 100% working, but i want to take re-review

2018년 12월 3일 (월) 23:27에 Shanqing Cai <notifications@github.com>님이 작성:

**Comment by caisq** [comment]
@rouismia The latest code still doesn't create alpha as a trainable weight.

**Comment by caisq** [comment]
Closing this PR in favor of https://github.com/tensorflow/tfjs-layers/pull/401

**Pull request closed without merging**
