### PR TITLE
Check the equality of tfjs version in dev and peer dependencies

### PR DESCRIPTION
**Pull request by caisq**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/123)

### CODE REVIEW

**Comment by tafsiri** [comment]
:lgtm_strong:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/123#-:-L9p88tkAWlzZKsPm_01:b-jbsf8z)*

**Comment by caisq** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[scripts/make-version, line 18 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/123#-L9pCaXr109Vg2r7Yr_t:-L9pEDVz74J861Kvxczt:b8qgo3r) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/34f3cc5d384a0d6b8dfa6e3c0ea0ee1cb508dda5/scripts/make-version#L18)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

I wouldn't do this in this file, let's make a unit test for this so you catch it in trvais

See: https://github.com/tensorflow/tfjs-core/blob/master/src/version_test.ts
</blockquote></details>

Yes, that would be more robust. But any idea on how to check both the dev and peer core versions from layers code?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/123)*

**Comment by nsthorat** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[scripts/make-version, line 18 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/123#-L9pCaXr109Vg2r7Yr_t:-L9pErzlDNmaDeuhkldE:b-fw6abj) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/34f3cc5d384a0d6b8dfa6e3c0ea0ee1cb508dda5/scripts/make-version#L18)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

Yes, that would be more robust. But any idea on how to check both the dev and peer core versions from layers code?
</blockquote></details>

You should be able to read the whole package JSON via require like the link from above so you can assert the versions match

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/123)*

**Comment by caisq** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[scripts/make-version, line 18 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/123#-L9pCaXr109Vg2r7Yr_t:-L9pPR5173IULY9SpeqO:b-ci589v) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/34f3cc5d384a0d6b8dfa6e3c0ea0ee1cb508dda5/scripts/make-version#L18)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

You should be able to read the whole package JSON via require like the link from above so you can assert the versions match
</blockquote></details>

Maybe I'm missing something, but the karma tests run in the browser. So fs.readFile and fs.readFileAsync are not defined. We can't read the package.json file from the tests.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/123)*

**Comment by nsthorat** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[scripts/make-version, line 18 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/123#-L9pCaXr109Vg2r7Yr_t:-L9pQehp6w2ZRXEWS1xF:bu6tsnj) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/34f3cc5d384a0d6b8dfa6e3c0ea0ee1cb508dda5/scripts/make-version#L18)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

Maybe I'm missing something, but the karma tests run in the browser. So fs.readFile and fs.readFileAsync are not defined. We can't read the package.json file from the tests.
</blockquote></details>

See this line:

https://github.com/tensorflow/tfjs-core/blob/master/src/version_test.ts#L23

You can require package.json and karma / ts will include it during browserification. Once you've included package.json it will be an object and you should be able to read any field (like version in this example - in your example you'll read dev deps and peer deps, find the key of @tensorflow/tfjs-core and assert the versions match)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/123)*

**Comment by caisq** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[scripts/make-version, line 18 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/123#-L9pCaXr109Vg2r7Yr_t:-L9pS3wp6nzbl4cGm081:b51yd37) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/34f3cc5d384a0d6b8dfa6e3c0ea0ee1cb508dda5/scripts/make-version#L18)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

See this line:

https://github.com/tensorflow/tfjs-core/blob/master/src/version_test.ts#L23

You can require package.json and karma / ts will include it during browserification. Once you've included package.json it will be an object and you should be able to read any field (like version in this example - in your example you'll read dev deps and peer deps, find the key of @tensorflow/tfjs-core and assert the versions match)
</blockquote></details>

Ah. got it. thanks!

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/123)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/123#-:-L9pTSdw6oWBysLYzqwI:b-jbsf8z)*

**Pull request merged**
