### PR TITLE
Remove K.ndim in favor of .rank on Tensors/SymbolicTensors

### PR DESCRIPTION
**Pull request by ericdnielsen**
Introduce a 'rank' property on SymbolicTensor so that it matches Tensor.  Then remove tfjs_backend's ndim(x)=> x.shape.length.  Use x.rank anywhere we had ndim(x).

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/200)

### CODE REVIEW

**Comment by caisq** [comment]
Review status: 0 of 11 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/types_test.ts, line 29 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/200#-LCvfYmP91f7C81JT7XU:-LCvfYmP91f7C81JT7XV:b-jals3d) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/785a8fed8d5ed307cd864b60d02222c477f79493/src/types_test.ts#L29)):*
> ```
> expect(st1.rank).toEqual(2);
> ```

This looks good. But I feel the need to have a unit test covering the edge case of the rank of a scalar tensor being 0. Can you add such a test to this file?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/200)*

**Comment by ericdnielsen** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/types_test.ts, line 29 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/200#-LCvfYmP91f7C81JT7XU:-LD1uen858r49tBV607a:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/785a8fed8d5ed307cd864b60d02222c477f79493/src/types_test.ts#L29)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> expect(st1.rank).toEqual(2);
> ```

This looks good. But I feel the need to have a unit test covering the edge case of the rank of a scalar tensor being 0. Can you add such a test to this file?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/200)*

**Comment by bileschi** [comment]
*[src/types.ts, line 77 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/200#-LD2G_oj0MhePNKolu5s:-LD2G_okAHRqDUfmFfZZ:bprvywb) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/3914d46c4f142988f348e6253e4a68378870f888/src/types.ts#L77)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>   constructor(
>       readonly dtype: DataType, readonly shape: Shape,
>       public sourceLayer: Layer, readonly inputs: SymbolicTensor[],
>       readonly callArgs: Kwargs, name?: string,
>       readonly outputTensorIndex?: number) {
> ```
</details>

Unrelated, but why does the SymbolicTensor creation signature include all these parameters that are unused?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/200)*

**Comment by ericdnielsen** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/types.ts, line 77 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/200#-LD2G_oj0MhePNKolu5s:-LD2Ja52Bcg4_3Ozmjg0:b-z2ivb7) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/3914d46c4f142988f348e6253e4a68378870f888/src/types.ts#L77)):*
<details><summary><i>Previously, bileschi (Stanley Bileschi) wrote…</i></summary><blockquote>

> ```
>   constructor(
>       readonly dtype: DataType, readonly shape: Shape,
>       public sourceLayer: Layer, readonly inputs: SymbolicTensor[],
>       readonly callArgs: Kwargs, name?: string,
>       readonly outputTensorIndex?: number) {
> ```
Unrelated, but why does the SymbolicTensor creation signature include all these parameters that are unused?
</blockquote></details>

Discussed offline, but all the readonly arguments are accessible via .shape style acessors on the SymbolicTensor object.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/200)*

**Comment by bileschi** [comment]
:lgtm_strong:

---

Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/200#-:-LD7P3zO1l0-ybmg5O_1:b-jbsf8z)*

**Pull request merged**
