### PR TITLE
Implement logic for stopTraining in tf.Model.fit()

### PR DESCRIPTION
**Pull request by caisq**
* so that callbacks can set `this.model.stopTraining` to order
  early stopping of training.

Fixes: https://github.com/tensorflow/tfjs/issues/312

FEATURE: Support early stopping of training by `Callback`s.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/213)

### CODE REVIEW

**Comment by bileschi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/engine/training.ts, line 1234 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/213#-LDgJAKi7010iUiSK1h9:-LDgJAKi7010iUiSK1hA:b-tw1khs) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/c1e338a1ad774822a9e885be10aebe32fa331af4/src/engine/training.ts#L1234)):*
> ```
>  // TODO(cais): Take care of the PyKeras logic of stop_training.
> ```
Can this comment now be removed?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/213)*

**Comment by bileschi** [comment]
:lgtm_strong:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/213#-:-LDgMwKb9MUrFnmm_O-I:b-jbsf8z)*

**Comment by davidsoergel** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/engine/training.ts, line 647 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/213#-LDgYy6AC8SBHmkz7eog:-LDgYy6AC8SBHmkz7eoh:b-4c1jxl) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/c1e338a1ad774822a9e885be10aebe32fa331af4/src/engine/training.ts#L647)):*
> ```XML
>   // A public property that can be set by Callbacks to order early stopping
>   // during `fit()` calls.
>   stopTraining: boolean;
> ```

This seems like a strange way to pass information from the callback.  What about letting the callbacks return a boolean?  Or, pass a requestStop() callback to the callback, etc.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/213)*

**Comment by caisq** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/engine/training.ts, line 647 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/213#-LDgYy6AC8SBHmkz7eog:-LDg_FNL-B_P49kN8Bly:b-ykx7qw) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/c1e338a1ad774822a9e885be10aebe32fa331af4/src/engine/training.ts#L647)):*
<details><summary><i>Previously, davidsoergel (David Soergel) wrote…</i></summary><blockquote>

This seems like a strange way to pass information from the callback.  What about letting the callbacks return a boolean?  Or, pass a requestStop() callback to the callback, etc.
</blockquote></details>

I agree with your point that this way is a little strange. But that's how Keras Callbacks are designed. Unfortunately at this point it's already a part of the API and we can't change it without breaking backward compatibility.

My 2 cents is that since it works, we should keep this slightly strange style to avoid introducing confusing inconsistency with (Python) Keras.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/213)*

**Comment by davidsoergel** [comment]
:lgtm_strong:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/engine/training.ts, line 647 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/213#-LDgYy6AC8SBHmkz7eog:-LDg_dhbEW0Bbbso695j:b32wtd) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/c1e338a1ad774822a9e885be10aebe32fa331af4/src/engine/training.ts#L647)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

I agree with your point that this way is a little strange. But that's how Keras Callbacks are designed. Unfortunately at this point it's already a part of the API and we can't change it without breaking backward compatibility.

My 2 cents is that since it works, we should keep this slightly strange style to avoid introducing confusing inconsistency with (Python) Keras.
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/213#-:-LDg_haBB1Clqs7OPY1X:b-jbsf8z)*

**Comment by caisq** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/engine/training.ts, line 1234 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/213#-LDgJAKi7010iUiSK1h9:-LDh0wllB4nzMhsnKjb7:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/c1e338a1ad774822a9e885be10aebe32fa331af4/src/engine/training.ts#L1234)):*
<details><summary><i>Previously, bileschi (Stanley Bileschi) wrote…</i></summary><blockquote>

> ```
>  // TODO(cais): Take care of the PyKeras logic of stop_training.
> ```
Can this comment now be removed?
</blockquote></details>

Done.

---

*[src/engine/training_test.ts, line 1130 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/213#-LDgMFqL7JOHy0zhN_EG:-LDh2wTu0tCIscyQj_u3:bt2dn0t) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/c1e338a1ad774822a9e885be10aebe32fa331af4/src/engine/training_test.ts#L1130)):*
<details><summary><i>Previously, bileschi (Stanley Bileschi) wrote…</i></summary><blockquote>

> ```
> batchs 
> ```
batches

Also, you might want to replace `numSamples` with `5` here, since numSamples is set hundreds of lines above, but knowing the value is critical to understanding this sentence.


</blockquote></details>

I added a comment here to talk about the value of numSamples. I think redefining the variable will make the code more complicated than necessary.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/213)*

**Pull request merged**
