### PR TITLE
Expose tf.metrics; Add binaryCrossentropy metric

### PR DESCRIPTION
**Pull request by caisq**
Fixes: https://github.com/tensorflow/tfjs/issues/208

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/144)

### CODE REVIEW

**Comment by nsthorat** [comment]
:lgtm_strong:

Nice!

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/exports.ts, line 868 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/144#-LAmj2mx9-NCR_A6jl1O:-LAmij17-yAWSXLz9pw3:b28svhj) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/a7dcbfee145f7ee518841867d941f1e83e61be76/src/exports.ts#L868)):*
> ```XML
> }
> 
> export class MetricExports {
> ```

since this isn't actually doing anything, consider putting this class inside losses to reduce the stack trace. optional because I understand if you want to keep it symmetric.

---

*[src/losses.ts, line 22 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/144#-LAmjLIP5FAiAjbm7LME:-LAmjLIP5FAiAjbm7LMF:bglaci) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/a7dcbfee145f7ee518841867d941f1e83e61be76/src/losses.ts#L22)):*
> ```XML
>  * Loss or metric function: Mean squared error.
>  *
>  * Example:
> ```

you can remove "Example:" here and below

---

*[src/losses.ts, line 32 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/144#-LAmjOdK6e1lDEtlKXTa:-LAmjOdL28IYmrqpcvmM:b-j5mmnu) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/a7dcbfee145f7ee518841867d941f1e83e61be76/src/losses.ts#L32)):*
> ```XML
>  * Aliases: `tf.metrics.MSE`, `tf.metrics.mse`.
>  *
>  * @param yTrue Truth `Tensor`.
> ```

remove backticks here and below (the type comes through automatically so this becomes redundant)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/144#-:-LAmjV707K_xgzydit11:b-79rzop)*

**Comment by nsthorat** [comment]
Obviously get travis to pass before merging

**Comment by caisq** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/exports.ts, line 868 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/144#-LAmj2mx9-NCR_A6jl1O:-LAmo4QX0sCSprvckqbB:bsrc3bg) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/a7dcbfee145f7ee518841867d941f1e83e61be76/src/exports.ts#L868)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

since this isn't actually doing anything, consider putting this class inside losses to reduce the stack trace. optional because I understand if you want to keep it symmetric.
</blockquote></details>

Yeah, let's keep it in exports.ts to make it consistent with the other exports.

---

*[src/losses.ts, line 22 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/144#-LAmjLIP5FAiAjbm7LME:-LAmoFxG3qeZAKitHy4J:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/a7dcbfee145f7ee518841867d941f1e83e61be76/src/losses.ts#L22)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

you can remove "Example:" here and below
</blockquote></details>

Done.

---

*[src/losses.ts, line 32 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/144#-LAmjOdK6e1lDEtlKXTa:-LAmoR6Y5uG7JzSp9ysz:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/a7dcbfee145f7ee518841867d941f1e83e61be76/src/losses.ts#L32)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

remove backticks here and below (the type comes through automatically so this becomes redundant)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/144)*

**Comment by bileschi** [comment]
*[src/metrics_test.ts, line 56 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/144#-LAmqzJ03i2m4i4rJ30b:-LAmqzJ03i2m4i4rJ30c:b-r74mnm) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/c8df10cc8047f3e74e215991231e70ac89f45b43/src/metrics_test.ts#L56)):*
> ```
>                          1.00000015e-07, 6.93147182e-01, 1.59423847e+01,
>                          1.61180954e+01, 6.93147182e-01, 1.19209332e-07
> ```
Just a suggestion.  These values are difficult to visually evaluate for correctness.  Can you either express in a comment how they were determined or select an example that is easy to mentally calculate?  If not, no big deal.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/144)*

**Comment by bileschi** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/losses.ts, line 172 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/144#-LAmq-1R8_6HnWBUO5nR:-LAmq-1R8_6HnWBUO5nS:bm2srnb) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/c8df10cc8047f3e74e215991231e70ac89f45b43/src/losses.ts#L172)):*
> ```
> normalize
> ```
nit normalizes (with 's')

---

*[src/metrics.ts, line 65 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/144#-LAmqYE0-X26UNZTZ6zq:-LAmqYE0-X26UNZTZ6zr:b-a1s3bh) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/c8df10cc8047f3e74e215991231e70ac89f45b43/src/metrics.ts#L65)):*
> ```XML
>  * accuracy.print();
>  * ```
>  *
> ```

Maybe add something here about how the largest value in the prediction is interpreted to be the class?  Also, what is the behavior in the event of a tie?  

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/144)*

**Comment by caisq** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/losses.ts, line 172 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/144#-LAmq-1R8_6HnWBUO5nR:-LAmvjQP9MRFbE526bqv:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/c8df10cc8047f3e74e215991231e70ac89f45b43/src/losses.ts#L172)):*
<details><summary><i>Previously, bileschi (Stanley Bileschi) wrote…</i></summary><blockquote>

> ```
> normalize
> ```
nit normalizes (with 's')
</blockquote></details>

Done.

---

*[src/metrics.ts, line 65 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/144#-LAmqYE0-X26UNZTZ6zq:-LAmufCl4wIMKAJX79sI:b-n19a4u) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/c8df10cc8047f3e74e215991231e70ac89f45b43/src/metrics.ts#L65)):*
<details><summary><i>Previously, bileschi (Stanley Bileschi) wrote…</i></summary><blockquote>

Maybe add something here about how the largest value in the prediction is interpreted to be the class?  Also, what is the behavior in the event of a tie?  
</blockquote></details>

The behavior of this metric in cases where there are values outside the [0, 1] internal seems to be undefined. By a tie, do you mean a value like 0.5? If so, 0.5 is interpreted as 1. Added this to doc string.

---

*[src/metrics_test.ts, line 56 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/144#-LAmqzJ03i2m4i4rJ30b:-LAmsGnM6gdH8oVY26FG:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/c8df10cc8047f3e74e215991231e70ac89f45b43/src/metrics_test.ts#L56)):*
<details><summary><i>Previously, bileschi (Stanley Bileschi) wrote…</i></summary><blockquote>

> ```
>                          1.00000015e-07, 6.93147182e-01, 1.59423847e+01,
>                          1.61180954e+01, 6.93147182e-01, 1.19209332e-07
> ```
Just a suggestion.  These values are difficult to visually evaluate for correctness.  Can you either express in a comment how they were determined or select an example that is easy to mentally calculate?  If not, no big deal.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/144)*

**Comment by bileschi** [comment]
*[src/metrics.ts, line 65 at r2](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/144#-LAmqYE0-X26UNZTZ6zq:-LAnA0iVA77Mj5HI-ZLi:b-pubeef) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/c8df10cc8047f3e74e215991231e70ac89f45b43/src/metrics.ts#L65)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

The behavior of this metric in cases where there are values outside the [0, 1] internal seems to be undefined. By a tie, do you mean a value like 0.5? If so, 0.5 is interpreted as 1. Added this to doc string.
</blockquote></details>

I don't think 0.5 has any special behavior here, right? the K.argmax returns the position with maximum value, it seems?   I guess what I'm curious about is whether

categoricalAccuracy([1, 0], [.3, .3])
is any different from 
categoricalAccuracy([0, 1], [.3, .3])

and if that's a problem.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/144)*

**Pull request merged**
