### PR TITLE
Adds tidy() to qr decomposition function

### PR DESCRIPTION
**Pull request by bileschi**
Possibly addresses issue #245.

Checked that fewer Tensors were allocated during tests (6 vs. 70 for a very small problem).

Related to https://github.com/tensorflow/tfjs/issues/245

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/158)

### CODE REVIEW

**Comment by nsthorat** [comment]
:lgtm_strong:

Awesome (wait for @cais since I don't know this code).

One useful unit test you can add to your tests:
https://github.com/tensorflow/tfjs-layers/blob/master/src/backend/tfjs_backend_test.ts#L1431

Something like this:

```
  it('doesnt leak memory', () => {
    const x = tensor2d([[1, 3], [-2, -4]], [2, 2]);
    const numTensors = tf.memory().numTensors;
    const [q, r] = K.qr(x);
    // ...
    expect(tf.memory().numTensors).toEqual(numTensors + 2);
  });
```

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/158#-:-LBLeuJM80cTsd366w0R:b-ukzwj5)*

**Comment by caisq** [comment]
Thanks for looking into this, Stan. See comment below.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[src/backend/tfjs_backend.ts, line 1125 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/158#-LBLoNUABb29Cbc47_in:-LBLoNUABb29Cbc47_io:b-u9iqp1) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/14fc20bb7af60dc9a210a19f0533b79272d53395/src/backend/tfjs_backend.ts#L1125)):*
> ```
> return tidy(() => {
> ```

Can you try putting this tidy() scope inside the for look below? This will further reduce the instantaneous memory usage. I'm not sure if there is going to be any significant improvement if you put it here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/158#-:-LBLoIKN7myMDem4HyTL:b-c5hceh)*

**Comment by caisq** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/backend/tfjs_backend.ts, line 1125 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/158#-LBLoNUABb29Cbc47_in:-LBLocuJAyw7KeqKb6RB:bp4gjdh) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/14fc20bb7af60dc9a210a19f0533b79272d53395/src/backend/tfjs_backend.ts#L1125)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> return tidy(() => {
> ```

Can you try putting this tidy() scope inside the for look below? This will further reduce the instantaneous memory usage. I'm not sure if there is going to be any significant improvement if you put it here.
</blockquote></details>

Sorry, I meant "for loop".

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/158)*

**Comment by nsthorat** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/backend/tfjs_backend.ts, line 1125 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/158#-LBLoNUABb29Cbc47_in:-LBLpbou6wyjYZHj7a_l:bxq22l5) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/14fc20bb7af60dc9a210a19f0533b79272d53395/src/backend/tfjs_backend.ts#L1125)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

Sorry, I meant "for loop".
</blockquote></details>

+1, I didn't suggest this because this is already a step in the right direction. Putting the tidy() inside the for loop will require a little rework. The inner tidy() should return an array of [w, r, q] and reassign. You can do it like this:

```js
[w, r, q] = tf.tidy(() => {
   // Compute w, r, q
   return [w, r, q];
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/158)*

**Comment by nsthorat** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/backend/tfjs_backend.ts, line 1125 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/158#-LBLoNUABb29Cbc47_in:-LBLpuAe7XDvpK2KpCyQ:bh480qy) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/14fc20bb7af60dc9a210a19f0533b79272d53395/src/backend/tfjs_backend.ts#L1125)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

+1, I didn't suggest this because this is already a step in the right direction. Putting the tidy() inside the for loop will require a little rework. The inner tidy() should return an array of [w, r, q] and reassign. You can do it like this:

```js
[w, r, q] = tf.tidy(() => {
   // Compute w, r, q
   return [w, r, q];
```
</blockquote></details>

Can't edit my comment, obviously there's a `}` at the end.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/158)*

**Comment by caisq** [comment]
:lgtm_strong:

Thanks!

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/backend/tfjs_backend_test.ts, line 1479 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/158#-LBRx_FD4oHQ6uPEGUK5:-LBRx_FD4oHQ6uPEGUK6:bph5sj8) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/2740aaa4717ce36f1f97d94e98634c4380332499/src/backend/tfjs_backend_test.ts#L1479)):*
> ```
> + 2
> ```

Can you add a one-line comment describing why the number `2` here? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/158#-:-LBRxdEo6xYcTVZyg1Dd:b-afugb9)*

**Comment by caisq** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/backend/tfjs_backend_test.ts, line 1479 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/158#-LBRx_FD4oHQ6uPEGUK5:-LBRxg5B1EICBMVkP0is:b-g00fgg) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/2740aaa4717ce36f1f97d94e98634c4380332499/src/backend/tfjs_backend_test.ts#L1479)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> + 2
> ```

Can you add a one-line comment describing why the number `2` here? 
</blockquote></details>

Never mind. You already did that.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/158)*

**Comment by bileschi** [comment]
*[src/backend/tfjs_backend_test.ts, line 1479 at r3](https://reviewable.io/reviews/tensorflow/tfjs-layers/158#-LBRx_FD4oHQ6uPEGUK5:-LBS3sZ3EVzacg1AVQFF:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/2740aaa4717ce36f1f97d94e98634c4380332499/src/backend/tfjs_backend_test.ts#L1479)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

Never mind. You already did that.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/158)*

**Comment by bileschi** [comment]
:D   

---







*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/158#-:-LBS3vDC3SZxCPns_Bmv:b-8fhhe7)*

**Comment by bileschi** [comment]
*[src/backend/tfjs_backend.ts, line 1125 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/158#-LBLoNUABb29Cbc47_in:-LBS3rhW-e2_ie4MPQdp:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/14fc20bb7af60dc9a210a19f0533b79272d53395/src/backend/tfjs_backend.ts#L1125)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

Can't edit my comment, obviously there's a `}` at the end.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/158)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/models_test.ts, line 524 at r4](https://reviewable.io/reviews/tensorflow/tfjs-layers/158#-LBW6nWb23j5DC5M2E0K:-LBW6nWb23j5DC5M2E0L:b-1fk4rz) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/ccedf826b27f7ccb3a3c9816d7435f71df956e72/src/models_test.ts#L524)):*
> ```XML
> // TODO(bileschi): Uncomment once we are able to load a model of this size.
> /*
> const fakeRNNModel: ModelAndWeightsConfig = {
> ```

is this meant to be part of this PR?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/158#-:-LBW6pkp3UXY2ztPDc3K:b-jbsf8z)*

**Comment by caisq** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/models_test.ts, line 524 at r4](https://reviewable.io/reviews/tensorflow/tfjs-layers/158#-LBW6nWb23j5DC5M2E0K:-LBW704P38yFFX9ITEJu:b-y5m5af) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/ccedf826b27f7ccb3a3c9816d7435f71df956e72/src/models_test.ts#L524)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

is this meant to be part of this PR?
</blockquote></details>

Yeah, I suggested Stan keep this in so it can used for testing  loading a relatively large LSTM layer with orthogonal initializer when the bug is fixed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/158)*

**Pull request merged**
