### PR TITLE
Added Upsampling2d layer

### PR DESCRIPTION
**Pull request by seranus**
Added upsampling2d layer for 4d tensors

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/204)

### CODE REVIEW

**Comment by seranus** [comment]
I signed it!

**Comment by caisq** [comment]
Thanks, @seranus ! Overall it looks great, but I have some requests for changes below. 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/layers/convolutional.ts, line 1095 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/204#-LD8g57O5lEZsyQM7i4q:-LD8g57P-mixXPV49ZTf:b-jw1lth) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/d9194311c690e90026e5aca0ad9aa864afa7abf3/src/layers/convolutional.ts#L1095)):*
> ```
> The upsampling factors for rows and columns.
> ```

Document the default: `[2, 2]`.

---

*[src/layers/convolutional.ts, line 1103 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/204#-LD8gH4hEdqKMp1uauTg:-LD8gH4iA1wCGtN5tqRu:b-namzdf) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/d9194311c690e90026e5aca0ad9aa864afa7abf3/src/layers/convolutional.ts#L1103)):*
> ```
> (
> ```

When describing shapes in JavaScript/TypeScript, use `[...]`, instead of `(...)`. The latter is from Python tuples, not applicable here.
Same below.

---

*[src/layers/convolutional.ts, line 1142 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/204#-LD8gU5q40p3gXz6-h4P:-LD8gU5q40p3gXz6-h4Q:b4z8txv) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/d9194311c690e90026e5aca0ad9aa864afa7abf3/src/layers/convolutional.ts#L1142)):*
> ```
>     this.size = config.size;
>     this.dataFormat =
> ```

You need the logic to set this.size as the default if config.size is null. Something like:

```js
// Outside constructor, as a class property.
readonly DEFAULT_SIZE = [2, 2];
```

```js
// Inside constructor:
this.size = config.size == null ? this.DEFAULT_SIZE : config.size;
```

---

*[src/layers/convolutional.ts, line 1145 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/204#-LD9xJhvA5J76VVGRzak:-LD9xJhvA5J76VVGRzal:bsahxlg) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/d9194311c690e90026e5aca0ad9aa864afa7abf3/src/layers/convolutional.ts#L1145)):*
> ```
>   }
> ```

Please also add this.inputSpec for input tensor being 4D. You can find examples in other layers.

---

*[src/layers/convolutional.ts, line 1180 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/204#-LD8h4-h9tiuklljQlEW:-LD8h4-h9tiuklljQlEX:b-56ixof) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/d9194311c690e90026e5aca0ad9aa864afa7abf3/src/layers/convolutional.ts#L1180)):*
> ```
> const config = { size: this.size, dataFormat: this.dataFormat };
> ```

It looks like you didn't run `yarn format`. Please run that before committing, so the code will have consistent style with the rest of the codebase.

---

*[src/layers/convolutional_test.ts, line 899 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/204#-LD9xwtu11rxSO0EhC_K:-LD9xwtu11rxSO0EhC_L:bm7tosj) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/d9194311c690e90026e5aca0ad9aa864afa7abf3/src/layers/convolutional_test.ts#L899)):*
> ```
> escribe('UpSampling2D Layer', (
> ```

The test here covers only Tensor inputs. Can you add a `describe` section for SymbolicTensor inputs, so as to exercise the computeOutputShape code. There are examples for that in the same file. 

---

*[src/layers/convolutional_test.ts, line 958 at r2](https://reviewable.io/reviews/tensorflow/tfjs-layers/204#-LD9xsm1DtYqXFd13ZXd:-LD9xsm1DtYqXFd13ZXe:bjz0pjz) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/d9194311c690e90026e5aca0ad9aa864afa7abf3/src/layers/convolutional_test.ts#L958)):*
> ```XML
>     expectTensorsClose(layer.apply(x, null) as Tensor, y);
>   });
> });
> ```

nit: add newline character at the end of the file.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/204#-:-LD9y6qr7j7IMhKceKGo:bgou64i)*

**Comment by caisq** [comment]
Gentle ping @seranus ?

**Comment by seranus** [comment]
Hey, kinda busy so I decided to finish it over the weekend, most likely I'll push it on sunday

**Comment by seranus** [comment]
Feel free to review my updates.

I had issues with format function because of spaces in folder name, I'd appreciate if it could be fixed

**Comment by caisq** [comment]
:lgtm_strong:

Thanks again, @seranus !

---

Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/204#-:-LDe3Dpk8Hn-ytGDVK2S:b-cd0noq)*

**Pull request merged**
