### PR TITLE
Use backward layer for computing yRev even when an initial state is given.

### PR DESCRIPTION
**Pull request by adarob**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/318)

### CODE REVIEW

**Comment by bileschi** [comment]
Thanks @adarob , it would have been nice if this bug had been exposed in a test.  Would it be possible / difficult to add a test that would be broken but for your fix?

**Comment by caisq** [comment]
@adarob, +1 to what @bileschi  if you are willing to add the test that would be great. We'll also be happy to merge this PR first and add a test ourselves. Just let us know. Thanks.

**Comment by caisq** [comment]
@bileschi Given we are planning a new minor release soon, I'll merge this PR first and add tests for it later. How does that sound?

**Comment by bileschi** [comment]
@caisq works for me.

**Comment by caisq** [comment]
@bileschi Thanks.

**Pull request merged**
