### PR TITLE
Moving serialization infrastructure to -core

### PR DESCRIPTION
**Pull request by ericdnielsen**
This is part of a paired PR (one in core, one in layers).

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/154)

### CODE REVIEW

**Comment by ericdnielsen** [comment]
This is updated to match the PR against core.  I've tested locally with yarn link/local-publish.

**Comment by caisq** [comment]
Review status: 0 of 29 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[package.json, line 9 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/154#-LBag2PU55kmTOix7XhY:-LBag2PU55kmTOix7XhZ:b-czwjuh) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/f47a1d8a84ef2e40f9af6c6726c0b1ffd2d6231a/package.json#L9)):*
> ```
> link:.yalc/@tensorflow/tfjs-core
> ```

Is this meant to be permanent? Or are you going to remove it before merging this PR?

As long as Travis tests pass, I'm happy with it. But beware that this means we'll have to start using branches for releases, because releases shouldn't depend on the HEAD.

---

*[package.json, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs-layers/154#-LBafsVk88QHpGOSpjGJ:-LBafsVk88QHpGOSpjGK:b-8jfmo6) ([raw file](https://github.com/tensorflow/tfjs-layers/blob/f47a1d8a84ef2e40f9af6c6726c0b1ffd2d6231a/package.json#L47)):*
> ```
> "dependencies": {}
> ```

Why is this necessary?

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/154)*

**Comment by caisq** [comment]
:lgtm_strong:

LGTM modulo questions about package.json.

---

Review status: 0 of 29 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/154#-:-LBah8e69x5jtlyoYaRW:b-t45sdv)*

**Comment by ericdnielsen** [comment]
Re-updated to head/linked against the updated core.  Ready for review.

**Pull request merged**
