### PR TITLE
Update switch-tfjs-core-version.sh (switch-deeplearn-version.sh)

### PR DESCRIPTION
**Pull request by caisq**
* Rename the file to reflect repo change.
* Replace deeplearn.js with tfjs-core in the script.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-layers/138)

### CODE REVIEW

**Comment by bileschi** [comment]
:lgtm_strong:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/138#-:-LAZAxqE1fwmB3iHToki:b-jbsf8z)*

**Comment by bileschi** [comment]
*[a discussion](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/138#-LAZAzXkCSzEDoYCubN9:-LAZAzXkCSzEDoYCubNA:b-wvc1vs) (no related file):*
Is it possible to achieve much of the same by changing the package.json file? 
- "@tensorflow/tfjs-core": "0.7.1",
+ "@tensorflow/tfjs-core": "git+git://github.com/tensorflow/tfjs-core.git#master"

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/138)*

**Comment by bileschi** [comment]
*[a discussion](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/138#-LAZAzXkCSzEDoYCubN9:-LAZBELo3MnsPL_4jw8M:blhokur) (no related file):*
<details><summary><i>Previously, bileschi (Stanley Bileschi) wrote…</i></summary><blockquote>

Is it possible to achieve much of the same by changing the package.json file? 
- "@tensorflow/tfjs-core": "0.7.1",
+ "@tensorflow/tfjs-core": "git+git://github.com/tensorflow/tfjs-core.git#master"

</blockquote></details>

This did not render the way I had hoped.  I intended something like a diff, get rid of the first line, add the second line

```
    - "@tensorflow/tfjs-core": "0.7.1",
    + "@tensorflow/tfjs-core": "git+git://github.com/tensorflow/tfjs-core.git#master"
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/138)*

**Comment by caisq** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/138#-LAZAzXkCSzEDoYCubN9:-LAZKEfH6aHxR6JpO9G-:bqq9gcv) (no related file):*
<details><summary><i>Previously, bileschi (Stanley Bileschi) wrote…</i></summary><blockquote>

This did not render the way I had hoped.  I intended something like a diff, get rid of the first line, add the second line

```
    - "@tensorflow/tfjs-core": "0.7.1",
    + "@tensorflow/tfjs-core": "git+git://github.com/tensorflow/tfjs-core.git#master"
```
</blockquote></details>

What you suggested is fine if one wants to use unmodified git repo at HEAD. But it doesn't help with the case in which one wants to make some changes to to HEAD of tfjs-core and depend on the modified version. In this sense, the approach here is more general. Later we could modify the script to do what  you suggested, but that will introduce two ways of linking against tfjs-core.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs-layers/138)*

**Pull request merged**
